### ISSUE TITLE
LSTM and chainer v2

### ISSUE THREAD

**Issue by ghost** [soskek/weight_normalization#1]
Is this implementation compatible with LSTM and chainer v2?

When I try to use it I get this error:

  File "/usr/local/lib/python3.4/dist-packages/chainer/links/connection/lstm.py", line 265, in __call__
    if self.upward.W.data is None:
AttributeError: 'Linear' object has no attribute 'W'

**Comment by soskek** [comment]
Thank you for reporting! I noticed a bug. I'll fix it in a few days.

**Comment by soskek** [comment]
Unfortunately, I can't find any simple extension to fix it. Specifically, the current implementation can't transform a chain with grand children parameters, e.g., LSTM. Transforming such chains can be realized by directly injecting my module into its `__init__`'s Linear.
